dist: trusty
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install: pip install .
script: python setup.py test
deploy:
- on:
    python: '3.6'
    tags: true
  provider: pypi
  distributions: 'bdist_wheel sdist'
  user: efl_phx
